export { default as About } from './components/pages/About';
export { default as Educations } from './components/pages/Educations';
export { default as Experiences } from './components/pages/Experiences';
export { default as Home } from './components/pages/Home';
export { default as Profile } from './components/pages/Profile';
export { default as Portfolios } from './components/pages/Portfolios';
export { default as Skills } from './components/pages/Skills';
export { default as Navbar } from './components/navbar/Navbar';
export { default as AppCss } from './App.css';
